language: elixir
elixir: 1.7.4
os: linux
dist: xenial

otp_release:
   - 22.0.5
   - 21.2.3
   - 20.3.8.5
   - 19.3

addons:
  apt:
    sources:
      - deadsnakes
    packages:
    - build-essential
    - curl
    - libcurl4-openssl-dev
    - libicu-dev
    - pkg-config
    - python3.6
    - python3.6-venv
    - python3-requests
    - python3-sphinx
#    - sphinx-rtd-theme
    - help2man
    - shunit2
    - autoconf2.13
    - yasm

git:
  depth: 10

# logfile uploader uses requests
cache:
  - pip

# logfile uploader credentials
env:
  global:
    - secure: "UdA/gKIlyuXaW+hUgRx40t1TYjLCGxMqHvM5Uw7UbUH2dqEkgJiLfhZGchS1JVzl8M01VKZUUzS7v2nvRLiHZN1kvaw5kfq31VRoafUah8jfmvqNWZVdLovHl3aw5UX/HRt0RkbWbhdbdknTfh6+YinSZ+Nb54jCErMg9nabXtM="
    - COUCHDB_IO_LOG_DIR=/tmp/couchjslogs

# Enable this block if you want to build docs & fauxton too
#node_js:
#  - 6
#before_script:
#  - ./configure -c

# Then comment this section out
before_script:
  - kerl list installations
  - rm -rf /tmp/couchjslogs
  - mkdir -p /tmp/couchjslogs
  - mkdir -p /tmp/spidermonkey
  - cd /tmp/spidermonkey
  - wget http://ftp.mozilla.org/pub/firefox/releases/60.3.0esr/source/firefox-60.3.0esr.source.tar.xz
  - tar -xf firefox-60.3.0esr.source.tar.xz
  - cd firefox-60.3.0/js/src
  - export SHELL=/bin/bash
  - mkdir obj && cd obj
  - ../configure --disable-ctypes --disable-ion --disable-jemalloc --enable-optimize --enable-posix-nspr-emulation --enable-hardening --with-system-zlib --with-intl-api
  - make -j4 && sudo make install
  - ls -lrt /usr/local/lib
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - cd /home/travis/build/apache/couchdb
  - ./configure -c --disable-docs --disable-fauxton
  - python3.6 -m venv /tmp/.venv
  - source /tmp/.venv/bin/activate

script:
   - make check

after_failure:
  - build-aux/logfile-uploader.py

# start a push build on master and release branches + PRs build on every branch
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^\d+\.x\.x$/
    - /^\d+\.\d+\.x$/

# Re-enable once test suite is reliable
#notifications:
#  email: false
#  irc:
#    channels:
#      "irc.freenode.org#couchdb-dev"
#  on_success: change
#  on_failure: always
#  use_notice: true
#  skip_join: true
#  template:
#    - %{repository_slug}/%{branch}: %{message} %{build_url}"
